# Generated by Django 5.1.2 on 2025-01-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='media_type',
        ),
    ]
