# Generated by Django 5.1.6 on 2025-02-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_post_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
